### ISSUE TITLE
How to build?

### ISSUE THREAD

**Issue by xlar54** [megis7/Me-Operating-System#1]
I didnt see a makefile or instructions on building.  Can you add this?

**Comment by michalismeng** [comment]
Hello @xlar54,

Unfortunately the build procedure I currently use is a bit lengthy (no makefile and windows-only), since it is much tied with the bootloading phase and a special initrd that needs to be created through a third program.

I will be adding the build scripts and updating the readme with instructions soon.

Feel free to contact me for any details.
